# Generated by Django 3.1.2 on 2021-09-19 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210919_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/certificates/')),
                ('issued_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profpic',
            field=models.ImageField(default='media/profpics/avatar.jpg', upload_to='media/profpics/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to='media/projects/'),
        ),
        migrations.DeleteModel(
            name='Certifications',
        ),
        migrations.AddField(
            model_name='certification',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.freelancer'),
        ),
    ]
