# Generated by Django 3.1.2 on 2021-09-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210919_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='education',
            field=models.CharField(default='engineering', max_length=1000),
        ),
    ]
