# Generated by Django 3.1.2 on 2021-09-19 08:50

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210919_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='languages',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), default=' ', max_length=510, size=10),
        ),
    ]
