# Generated by Django 3.1.2 on 2021-09-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210919_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('comment', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.client')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.freelancer')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
